server:
  port: 8077

eureka:
  client:
    # 拉取服务注册信息间隔（默认30秒）
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone : http://dev:dev@localhost:8079/eureka/

logging:
  config: classpath:logback-dev.xml
  level:
    org.springframework.cloud.gateway: debug