server:
  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    # 是否获取注册信息
    fetch-registry: false
    # 是否注册到eureka
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
