server:
  port: 8079

spring:
  security:
    user:
      name: dev
      password: dev

eureka:
  client:
    # 是否获取注册信息
    fetch-registry: false
    # 是否注册到eureka
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://dev:dev@localhost:${server.port}/eureka/

logging:
  config: classpath:logback-dev.xml