spring:
  application:
    name: service-center
  profiles:
    active: dev

#eureka:
#  server:
    # 自我保护机制
#    enable-self-preservation: false
    # 集群节点之间读取超时时间。单位：毫秒
#    peer-node-read-timeout-ms: 1000
