server:
  port: 8078

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: false
    registryFetchIntervalSeconds: 30
    serviceUrl:
     defaultZone: http://dev:dev@localhost:8079/eureka/

logging:
  config: classpath:logback-dev.xml